### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by leonardosnt**

### CODE REVIEW

**Comment by 0-Eclipse-0** [comment]
Thanks

**Comment by leonardosnt** [comment]
:D

**Comment by 0-Eclipse-0** [comment]
Well that was a fast reply

**Comment by leonardosnt** [comment]
:laughing: 



(I saw this today)

**Comment by 0-Eclipse-0** [comment]
: +1

**Comment by 0-Eclipse-0** [comment]
:)

**Pull request merged**
